### PR TITLE
Gem is throwing exception on *all* requests due to old ca-cert bundle from 3 years ago

### PR DESCRIPTION
**Pull request by bmuller**
Sendgrid updated their cert, and now this Gem fails on all requests.

### CODE REVIEW

**Comment by JEG2** [comment]
Can we please split the ruby-version details into a separate pull request?  Thanks!

**Comment by bmuller** [comment]
Your gem is broken and is causing errors in who knows how many 
production systems (including ours). You are free to cherry-pick as you 
see fit for as many merges as you'd like.

**Comment by JEG2** [comment]
I no longer use this gem.  Would you like to takeover maintenance of it?

I can split your pull requests apart, yes.  I was asking if you could save me some effort.  I'll assume your answer is, "No."

**Comment by bmuller** [comment]
Sure, I can take over maintenance.  

You can merge from my fork w/ no effort at all, and two commits will show up in the revision history all nice and neat.

**Comment by JEG2** [comment]
I am aware how Git an GitHub work, Brian.  :smile:

I would prefer your second commit didn't contain `.gitignore` changes, the addition of a `Gemfile`, etc. while also addressing the static certificate file.

But, you're in charge now.  :smile:

Shall I just add you as a contributor or would you prefer I transfer the repo to you?

**Comment by bmuller** [comment]
Understood.  This was a rushed emergency hotfix since our commercial product was effectively disabled by the gem's outdated cert bundle.

If you want to transfer the ownership of the gem on rubygems and on github then I can take over responsibility.

**Comment by JEG2** [comment]
You should have ownership in both places now.  Thanks for the help!

**Comment by bmuller** [comment]
Great!  Thank you for your contribution to open source!

Btw - speaking of open source - I noticed that there's no explicit license in the code.  Are you OK with making all of the code you wrote available under a MIT license (or is there another copyleft license you'd prefer)?

Thanks again!

**Comment by JEG2** [comment]
MIT is fine.  Go for it.

**Comment by bmuller** [comment]
Great!  Thanks again!

**Pull request merged**
