### PR TITLE
make ruby 1.8.7 compatible

### PR DESCRIPTION
**Pull request by dennyabraham**
Hi,

I had to use this API for a client with some specific requirements of the existing codebase. I figured I'd be a good citizen and open a pull request. Please let me know if there are any changes you object to or any things I'll need to do before you accept this.
### I've introduced several changes:
- removing 1.9-specific syntax in favor of 1.8-compatibility (see: hash syntax)
- pulled in backports for 1.9 fixes
- added a configure block for initializers
- turned the gatling_gun class into a module
- added a client class to hold gatling_gun's previous functionality
- added bundler
- used bundler-style gemspec/rakefile/versioning
- whitespace changes. I know, I know.

I did **not** bump the version. I figured I'd leave that to you. It'll be at least a minor bump, unless you want me to delegate the pre-existing methods to the client object, which I am totally fine with.

:tophat:
:Denny

### CODE REVIEW

**Comment by JEG2** [comment]
I am OK with some of these changes.  Here are my thoughts though:
- What is Bundler buying us?  You switched gem spec classes.  For that we added a new dependency, but mine worked with just Ruby.  I don't see the gain.
- I'm fine that you used a 1.8 friendly syntax internally, but the README should stay with 1.9's syntax.  1.8's era is over and we need to be encouraging everyone to move on.
- The JSON dependency bums me out.  This is just to support 1.8, since 1.9 ships with it.  I guess it's a needed evil, but I wish we could get around it.
- The switch to a module also bugs me a bit.  What did we gain here over what I had?

The rest seems fine, for what it's worth.

The 1.8 call is tricky at this point.  We are very late in it's life cycle now.  Rails is dropping support for it in the next release.  The problem is that we had to ugly the code up (like with net/http fixes) to get it.  I'm just wondering if that's really worth it at this point.

Am I making sense?  Tell me your thoughts on these points.

**Comment by dennyabraham** [comment]
TBH, your points are all correct. It's not clear that these changes _should_ be merged upstream. The goal in submitting the request was to see if @okrb would find 1.8 support useful. A lot of the agencies whose projects we've taken over used 1.8 without the test coverage to trivialize a 1.9 migration, so it's helpful to have libraries to use as we identify the seams, flush out the suites, and futurize their applications.

I do have some specific thoughts about your points:
- Bundler was added with the assumption that it's in active use on a developer system so that, in some sense, it wasn't an additional dependency. If that's not always true and there are developers using isolate or rip, then it was a bad call to make. In any case, dependency management and isolation gets us a well-defined, repeatable environment for building the gem. Bundler itself gets us the niceties of gem building and versioning tasks.
- The hashrocket syntax is currently in the README so developers can use the examples directly as they are valid in both 1.8 and 1.9. I personally haven't switched to JSON-style hashes since I handle projects that use symbols as values, but if hashrockets are deprecated, it's best to revert the README
- Is there a sane way to conditionally include the json dependency? We can case on RUBY_VERSION, but I don't know enough about the algorithm that walks the dependency tree to say that it won't cause problems with some build or install processes. Also worth considering is whether json will remain in stdlib in ruby 2.0 rather than getting gemmed out in the modularization drive.
- This was probably too stylistic a change to request you pull in. It originally emerged as an artifact of removing the file reading logic when computing the version in the gemspec. I left it in as a namespace and collection place for the additional require's

Given your points and the current status of 1.8 as a legacy to move away from, I'd recommend against merging these changes. I'm actually not sure which, if any, changes are worth merging back.

**Comment by JEG2** [comment]
Hackrockets are not deprecated.  They are still needed if you use non-Symbol keys.  However, I do find 1.9's syntax much cleaner for keyword style arguments.

There isn't yet a way to conditionally include the JSON dependency, no.  You can't use RUBY_VERSION for this because that check would happen on your computer, when the gem is built, not when it is installed.

If I had any dependencies to manage, I would merge the Bundler change, but I just can't see it here.  I agree that it's pretty standard, but it is still a dependency.  I just don't see the gain.  Rake is already giving me gem building tasks.

I've slept on it and I really feel 1.8 is just too close to going out.  I see tons of libraries leaving it behind now.  1.9 has been production ready for a long time now.  I really think that ship has sailed at this point.

So, I am going to pass on these changes.

I don't in anyway mean to say that I don't appreciate your work here.  Thanks for sending it up and giving me the chance to think about it.

**Comment by dennyabraham** [comment]
No problem, we're in agreement.

**Pull request closed without merging**
